# Generated by Django 5.0.6 on 2024-07-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_scene_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
